deals/urls.py
from django.urls import path
from . import views

app_name = 'deals'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('deal/<slug:slug>/', views.deal_single, name='deal_detail'),
    path('like_comment/', views.like_comment, name='like_comment'),
    path('like_dislike/like/', views.like_deal, name='like_like'),
    path('like_dislike/dislike/', views.dislike_deal, name='like_dislike'),
    path('category/<slug:slug>/', views.deals_by_category, name='deals_by_category'),
    path('shop/<slug:slug>/', views.deals_by_shop, name='deals_by_shop'),
    path('categories/', views.all_categories, name='all_categories'),
    path('shops/', views.all_shops, name='all_shops'),
    path('search/', views.search_deals, name='search_deals'),
]

prace_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from deals.sitemaps import DealSitemap
from django.views.generic import TemplateView

sitemaps = {'deals': DealSitemap}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('deals.urls')),
    path('account/', include('account.urls')),
    # sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += [
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="preload" href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" as="font" crossorigin>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'slick/slick.css' %}">
{#    <link rel="stylesheet" href="{% static 'slick/slick-theme.css' %}"> Работает и без стилей #}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon_image/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_image/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_image/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon_image/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/favicon_image/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#ffffff">

    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">

  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-own py-2">
      <div class="container">
      <a class="navbar-brand" href="{% url 'deals:home' %}">
          <img src="{% static 'images/logo.png' %}" alt="" width="150">
      </a>
      <button class="navbar-toggler ml-auto mr-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-th-list"></i> Категории
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for category in categories_nav %}
              <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
              {% endfor %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'deals:all_categories' %}">Все категории</a>
              <a class="dropdown-item" href="{% url 'deals:all_shops' %}">Все магазины</a>
            </div>

          </li>
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">Link</a>#}
{#          </li>#}
        </ul>
        <form action="{% url 'deals:search_deals' %}" method="get" class="form-inline my-2 my-lg-0 mr-2">
          <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Поиск . . .">
                <div class="input-group-append">
                  <button class="btn btn-own" type="submit">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
          </div>
        </form>
      </div>
          {% if not request.user.is_authenticated %}
            <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-light login_in">Войти</button></a>
          {% else %}
              <div class="dropdown">
                <button id="profil" type="button" class="btn btn-outline-light dropdown-toggle login_in" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if request.user.profile.photo %}
                        <img class="rounded-circle profile-menu-image" src="{{ request.user.profile.photo.url }}">
                    {% else %}
                        <img class="rounded-circle profile-menu-image" src="{% static 'images/profile_logo.png' %}">
                    {% endif %}
                    <span class="align-middle ml-1">{{ request.user }}</span>
                </button>
              <div class="dropdown-menu dropdown-menu-right mt-1" aria-labelledby="profil">
                   <a class="dropdown-item" href="{% url 'profile' request.user %}">Профиль</a>
                   <a class="dropdown-item" href="{% url 'edit' %}">Настройки</a>
                   <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
              </div>
              </div>
          {% endif %}
    </div>
    </nav>
    <!-- End Navigation -->

    <div class="wrapper">
        {% block extra_header %}
        {% endblock %}
        <div class="section my-3">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- Footer -->
    <footer class="bg-dark">

      <!-- Footer Elements -->
      <div class="container">

      </div>
      <!-- Footer Elements -->

      <!-- Copyright -->
      <div class="text-center py-3 ">
          <span class="footer-text">© {% now "Y" %} Copyright - PriceRace.ru Все права защищены.</span>
      </div>
      <!-- Copyright -->
    <a id="button-scroll-up"></a>
    </footer>
    <!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'slick/slick.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

  </body>
</html>

templates/home_page.html
{% extends 'base.html' %}
{% load deals_tags %}

{% block title %}PriceRace.ru - Лучшие скидки и предложения на товары для любителей покупать дешевле{% endblock %}
{% block description %}Лучшие скидки и предложения на товары от настоящих людей PriceRace.ru{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">
            <div class="col-lg-9 order-1 article-section mb-5">
                {% for deal in deals_list %}
                <article class="deal-section my-3">
                    <div class="row my-2">
                        <div class="col-md-4">
                            <div class="product-box__image d-flex align-items-center justify-content-center">
                                {% if deal.image %}
                                    <a href="{{ deal.get_absolute_url }}"><img src="{{ deal.image.url }}" alt="{{ deal.name }}" class="img-fluid deal-image"></a>
                                {% else %}
                                    <a href="{{ deal.get_absolute_url }}"><img src="http://placehold.it/250x250" alt="product image" class="img-fluid"></a>
                                {% endif %}
                            </div>
                            <a href="{{ deal.link_to_shop }}" target="_blank"><button type="button" class="btn btn-outline-own my-2">К скидке <i class="fas fa-external-link-alt"></i></button></a>
                        </div>
                        <div class="col-md-8">
                            <div class="product-box__desc">
                                <div class="d-flex flex-row justify-content-center p-1" >
                            {% with click_counter=deal.like_counter session=request.session.click_deal deal_id=deal.id|stringformat:"i" %}
                                <div class="d-flex justify-content-between">
                                    <button class="btn-like-{{ deal_id }} btn btn-sm btn-minus focus shadow-none dislike" data-id="{{ deal.id }}" {% if request.user in deal.user_like.all or deal_id in session %}disabled{% endif %}><i class="fas fa-minus"></i></button>
                                </div>
                                <div class="d-block w-100 mx-1">
                                    <div class="progress h-100">
                                        <div id="progress-bar-{{ deal_id }}" class="progress-bar" role="progressbar" style="width: {{ click_counter }}0%" aria-valuenow="{{ click_counter }}" aria-valuemin="0" aria-valuemax="10"></div>
                                    </div>
                                </div>
                                    <div class="d-flex justify-content-between">
                                        <button class="btn-like-{{ deal_id }} btn btn-sm btn-plus focus shadow-none like"  data-id="{{ deal.id }}" {% if deal_id in session or request.user in deal.user_like.all %}disabled{% endif %}><i class="fas fa-plus"></i></button>
                                    </div>
                                    <div class="d-flex justify-content-between ml-1 rounded like-counter border">
                                        <span class="mx-1 counter_like_deal_{{ deal_id }}">{{ click_counter }}</span>
                                        <span class="mx-1 like-heart"><i class="fas fa-heartbeat"></i></span>
                                    </div>
                                {% endwith %}
                            </div>
                                <a href="{{ deal.get_absolute_url }}" class="product-box__title ">{{ deal.name }}</a>
                                <div class="mb-2">
                                    <span class="sale-price">{{ deal.price }} <i class="fas fa-ruble-sign"></i></span>
                                    {% if deal.oldprice %}
                                    <span class="regular-price">{{ deal.oldprice }} <i class="fas fa-ruble-sign"></i></span>
                                    {% endif %}
                                    {% if deal.discount_procent %}
                                    <span class="product-box__sticker">{{ deal.discount_procent }}%</span>
                                    {% endif %}
                                    {% if deal.shop %}
                                    <span class="deal-shop">от <a href="{{ deal.shop.get_absolute_url }}" class="text-decoration-none"> {{ deal.shop }}</a></span>
                                    {% endif %}
                                </div>
                                <div class="mb-2 pb-2 border-bottom d-flex">
                                    <span class="author-deal flex-fill"><a href="{{ deal.author.profile.get_absolute_url }}" class="text-decoration-none"> <i class="fas fa-user-edit"></i> {{ deal.author }}</a></span>
                                    <span class="deal-post-date flex-fill"><i class="far fa-calendar-alt"></i> {{ deal.create|date:"d.m.Y (H:i)" }}</span>
                                    <span class="deal-comments ml-3 flex-fill"><a href="{{ deal.get_absolute_url }}#comment-area" class="text-decoration-none"><i class="far fa-comments"></i> ({{ deal.comments.count }})</a></span>
                                </div>
                                <div>
                                    <span></span>
                                </div>
                                <p class="product-box__short-desc">{{ deal.description|safe|truncatechars_html:155|striptags }}</p>
                            </div>
                        </div>
                    </div>
                </article>
                {% endfor %}

                {% include 'includes/pagination.html' %}

            </div>
            <aside class="col-lg-3 order-2">
                <!-- Category -->
                <div class="category-sidebar mb-3">
                    <div class="section-title section-title--3 ">
                        <h3>Категории</h3>
                    </div>
                        <ul class="list-group list-group-flush">
                            {% for category in categories %}
                              <li class="list-group-item sidebar"><a href="{{ category.get_absolute_url }}" class="text-decoration-none">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                <!-- Hot Deals -->
                <div class="deals-slide_sidebar mb-3">
                <div class="section-title  mb-2">
                    <h3>Лучшие скидки</h3>
                </div>
                    <div class="sidebar-slider_home">
                        {% show_best_deals  10 %}
                    </div>
                    <div class="d-flex justify-content-center">
                        <span class="prev_arrow_home mr-3"><i class="far fa-arrow-alt-circle-down"></i></span>
                        <span class="next_arrow_home ml-3"><i class="far fa-arrow-alt-circle-up"></i></span>
                    </div>
                </div>
                <div class="deals-slide_sidebar mb-3">
                <div class="section-title  mb-2">
                    <h3>Лучшие магазины</h3>
                </div>
                    <div class="sidebar-slider_shops">
                        {% show_favorite_shops 10 %}
                    </div>
                    <div class="d-flex justify-content-center">
                        <span class="prev_arrow_shops mr-3"><i class="far fa-arrow-alt-circle-down"></i></span>
                        <span class="next_arrow_shops ml-3"><i class="far fa-arrow-alt-circle-up"></i></span>
                    </div>
                </div>
            </aside>
        </div>
    </div>
{% endblock %}